// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <math.h>
#include <RobertaFunctions/NEPODefs.h>


double ___item;
int _SensorPin_P = A0;
void setup()
{
    Serial.begin(9600); 
    ___item = analogRead(_SensorPin_P);
}

void loop()
{
}
